# Generated by Django 4.0.3 on 2022-09-14 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom_du_client', models.CharField(max_length=50)),
                ('prenom_du_client', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Magasinier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=50)),
                ('prix', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('quantite', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantite', models.PositiveIntegerField(default=0, null=True)),
                ('prix', models.PositiveIntegerField(default=0, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alimentation.produit')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('adresse', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quanti', models.PositiveIntegerField(default=0, null=True)),
                ('prix', models.PositiveIntegerField(default=0, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentation.produit')),
            ],
        ),
    ]
