# Generated by Django 4.0.3 on 2022-08-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom_du_client', models.CharField(max_length=50)),
                ('prenom_du_client', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Magasinier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=50)),
                ('prix', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('quantite', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id_vente', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentation.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentation.produit')),
            ],
        ),
    ]
