# Generated by Django 4.0.3 on 2022-10-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=50)),
                ('prix', models.IntegerField(default=0)),
            ],
        ),
    ]
