# Generated by Django 4.0.3 on 2022-08-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
