# Generated by Django 4.0.3 on 2022-08-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentation', '0003_alter_vente_date_alter_vente_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='quanti',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
