# Generated by Django 4.0.3 on 2022-08-10 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alimentation', '0004_commande_quanti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='id_commande',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alimentation.produit'),
        ),
    ]
